on: [push, pull_request]
name: Continuous Integration

jobs:
  build-core:
    name: Build .NET
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore .NET workloads
        run: dotnet workload restore

      - name: Restore Dependencies
        run: dotnet restore managed-midi.Core.slnf

      - name: Build Projects
        run: dotnet build managed-midi.Core.slnf

  build-framewrok:
    name: Build .NET Framework
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Restore Dependencies
        run: dotnet restore managed-midi.Windows.slnf

      - name: Build Projects
        run: msbuild managed-midi.Windows.slnf

  build-xamarin:
    name: Build Xamarin
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: |
          dotnet restore ./managed-midi.sln
          dotnet restore ./Commons.Music.Midi.DotNetCore/Commons.Music.Midi.DotNetCore.csproj

      - name: Build Projects
        run: |
          dotnet build ./managed-midi.sln
          dotnet build ./Commons.Music.Midi.DotNetCore/Commons.Music.Midi.DotNetCore.csproj
