on: [push, pull_request]
name: Continuous Integration

jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
        
      - name: Restore dependencies
        run: dotnet restore ./**/*.csproj
        
      - name: Build projects
        run: |
          dotnet build ./managed-midi.sln
          dotnet build ./Commons.Music.Midi.DotNetCore/Commons.Music.Midi.DotNetCore.csproj
