on: [push, pull_request]
name: Continuous Integration

jobs:
  build-core:
    name: Build .NET
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
  
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Install .NET iOS Workload
        run: dotnet workload install ios

      - name: Restore Dependencies
        run: dotnet restore managed-midi.Core.slnf

      - name: Build Projects
        run: dotnet build managed-midi.Core.slnf

  build-framework:
    name: Build .NET Framework
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Projects
        run: msbuild managed-midi.Windows.slnf -restore -p:RestorePackagesConfig=true

  build-xamarin:
    name: Build Xamarin
    runs-on: windows-2019
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Projects
        run: msbuild managed-midi.Xamarin.slnf -restore
